apiVersion: v1
kind: Pod

metadata:
  name: task-onfailure
  namespace: web-lab
  labels:
    app: task-onfailure
  
spec: 
  restartPolicy: OnFailure
  containers:
  - name: task
    image: busybox:1.36
    command:
      - sh
      - -c
      - 'echo task-fallito; exit 1'