Vagrant.configure("2") do |config|

  config.vm.hostname = "k3s-lab"

  config.vm.box = "generic/rocky9"

  config.vm.network "private_network", ip: "192.168.33.20"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "k3s-lab"
    vb.memory = "2048"
    vb.cpus = "2"
  end

end