apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-reader
  namespace: formazione-sou
---
apiVersion: rbac.authorization.k8s.io/v1 #api dedicate a rbac e v1
kind: Role
metadata:
  name: cluster-reader
  namespace: formazione-sou
rules:  #elenco di regole
  - apiGroups:
      - apps
    resources: #gruppi su cui agisce
      - deployments
    verbs: #azioni consentite
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding #collega serviceaccount e role
metadata:
  name: cluster-reader-binding
  namespace: formazione-sou
subjects: #a chi assegnare permessi
  - kind: ServiceAccount
    name: cluster-reader
    namespace: formazione-sou
roleRef: #che ruolo assegnare
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-reader