Vagrant.configure("2") do |config|

  config.vm.hostname = "jenkins-lab"

  config.vm.box = "generic/rocky9"

  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.synced_folder "./condivisa", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "jenkins-lab"
    vb.memory = "2048"
    vb.cpus = "2"
  end

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "step_1_es/site.yml"
      ansible.compatibility_mode = "2.0"
      ansible.vault_password_file = File.expand_path(
  "~/.ansible/jenkins_lab_vault_pass"
)
  end
end
