---
# Source: apache-webserver/templates/secret.yaml
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURORENDQWh5Z0F3SUJBZ0lVZXJXSDFpc2x6WWNCdTE0Nm9BRmRhQkFBQzFvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0d6RVpNQmNHQTFVRUF3d1FZWEJoWTJobExuZGxZbk5sY25abGNqQWVGdzB5TmpBNE1qWXdPVE15TXpaYQpGdzB5TnpBNE1qWXdPVE15TXpaYU1Cc3hHVEFYQmdOVkJBTU1FR0Z3WVdOb1pTNTNaV0p6WlhKMlpYSXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQy9QY2Jxd3ZZb3ZNVnFickQ5bTlVWXZSNUMKWXlCcDFMRTVKRDR0bmNzVFI3N0QwQjNjcU5WMUFhaHYyTzdnUmQ1WktWZ2hESnZ6bnh6Ry85b1lFdlpjTTY4aQpDL2piSVJFUjVGQVkxK0ZFK2FqeDdXekR4Z2pSSUNqMzUycnpwbElCbHAzYXdsMGRiQm9iaVZXbnNDR1hjanh4Ci84bUNoQkpZZDgrMFdRL1RGQXpLQTlHR2M0VFVzekRTRDhyN2tvYjdSaWo5NC9weExxMmpMRy8yR0FDWVlYN2EKVXQ1ejBwL3daUlJpeG41VXZ0RjRpUUxUckZMLzdXSE9saXNxNXF6eXVyMTdLdVNKUlRHRU44MmVmNXg0REJxUwpLa28xTFB5TVB6aUhyb0ZRTnRGTDd3MDB0WlEzQnVrd3ZEYURQSkRGNEJkSEdMRGJnSmtkS3QwVTZCYXhBZ01CCkFBR2pjREJ1TUIwR0ExVWREZ1FXQkJTdzFVYUJKWXJac2ttbTFhY1gxME5heXVhcmJUQWZCZ05WSFNNRUdEQVcKZ0JTdzFVYUJKWXJac2ttbTFhY1gxME5heXVhcmJUQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01Cc0dBMVVkRVFRVQpNQktDRUdGd1lXTm9aUzUzWldKelpYSjJaWEl3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFzQWlCRDJRM05zCkVFZlF3WktoUkw1REJMR2xNRFg2b09hSGJQN1dpbGNwZmhoZnkrWXREakhLSkpPMWdDNlZGZTgzc2ExUVVRUDMKL3RRR1lONFd6U093UytPZHpIalFGOFJCclNPUjlzUS8yNDdMWG8rMnFGZTY0Zzc5Z3huRzZZZTdDdldyeE1rOQpwc1FXOEFjTytJV2tYWjBPU0ZyNThzZGg3WWVMN1dudG1tSFhoUmJWemZpOVpveUQxbG1jb0xwd0lydnBSc20wCkpUMmtCSEVWR0tkZEdjeGd2ZkVXL3dTMXVZb0o2YU05VE5MWEtEWFdjeEpTZW5jZStLSi8xL1ArYk54RXJBNlEKVHMvejNEY09DTWp6QitLQmVGMVVIdXhlVThOV0xTS3l0TlpKVGIvU2tkQloyUWlQRU5Bc0IwRFN0NkVscVNpKwovUFYzTUI4QUtPZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQy9QY2Jxd3ZZb3ZNVnEKYnJEOW05VVl2UjVDWXlCcDFMRTVKRDR0bmNzVFI3N0QwQjNjcU5WMUFhaHYyTzdnUmQ1WktWZ2hESnZ6bnh6RwovOW9ZRXZaY002OGlDL2piSVJFUjVGQVkxK0ZFK2FqeDdXekR4Z2pSSUNqMzUycnpwbElCbHAzYXdsMGRiQm9iCmlWV25zQ0dYY2p4eC84bUNoQkpZZDgrMFdRL1RGQXpLQTlHR2M0VFVzekRTRDhyN2tvYjdSaWo5NC9weExxMmoKTEcvMkdBQ1lZWDdhVXQ1ejBwL3daUlJpeG41VXZ0RjRpUUxUckZMLzdXSE9saXNxNXF6eXVyMTdLdVNKUlRHRQpOODJlZjV4NERCcVNLa28xTFB5TVB6aUhyb0ZRTnRGTDd3MDB0WlEzQnVrd3ZEYURQSkRGNEJkSEdMRGJnSmtkCkt0MFU2QmF4QWdNQkFBRUNnZ0VBQmE2VkNPZVcvdzh3d2JYeWplNXNnK29taW9Gb2RxSFU5dERVQk1YeDY5WTYKQ0VFQzMzU29ERUhBTCthSm5tSGxDOUFnZlZ3NFlVek5HRC9hSDlTbkVOdm1RYTdmdGg4QzQxTUlhdHlMSmJkUgo1TnptMmpXTzVkWm5Sb3BQMFZlK2l3RTBiOG40NWZBT3pJVDY1YkJrSnh4RDh5Zk81R1pUMGVDK3dUOG8xYlFaCndrcnJjeHZuQmtYKy9IZmJreGxhQlA3WERpYnlDc0Njb2VnVVllZ3hFYjhBUTBFZk1DcVVpQzE4ZC9rSlpCME0Kb1dCWUlWajRLSko4a1RadE1BZ2lmZlZJVDNCSkljMFlNQU9mYVhGSGw5bmRlRDljdkdkb1MxUUpMMkRoWGduRAppUytJZlNIVmVHRG93bFJOWGFzS3ZlbTEwVTAzdllMOHc2a1BtQW0xb1FLQmdRRHpJZUlEMzBaRXhtWXc5dWNLCjhJdXZ2OE5mRzIvT0ZteHBnM0ZQdDFmSFN0Z3BXKzBFcXhBYzdkaUlaMmE4VDFsZVNWOGczaGJGc2tNWTNBVysKc0RIalRQMW9MenlZd2c1RFhobmx1WjRJK2s5aElmWmpWMllUMlgvOEN6T0xESjAxemJ5QWpnd3J5NVBsQlUvVwpOeDBTSUdnajJmWWQ5WGNLOUNvb1VVZmNxUUtCZ1FESlhOY1lRcDZLWVhvSjVZV3lMYWhjbkM4WmJVUng1bEczCjU4NGJsRis1eUR4RWhhVGdzVWRMb0RvSE9LOENucyt4SThYSmRVd1VZdkhhakxlWUM5VCsxb1laNHJJbzRmQ0gKSmJtMkRxUjY5RW1mRUNsdUVzT0NLWDFTbTE0dVRlR3F0T2N4UVdndkRERGpudDdkRWJlZTgycWVzTHEvbDFlNQpQZk90d3R6bXlRS0JnQVlOOGZMbXZIazU5NUdBbElCUlBTbERQVHBCRktldEowWDVYL2o4TjlOZXFjTmQ1cWtYCkdXK2UvS1ZvN2NZQ3M5Y0ZQTGswenB4ZHRBNEtiSm96Q1FyLy84OTRYYW53S3lyQ1RTTExYSVFjdDUxVG15OGUKSGd5Z2ZlOW8xLysrY0t2R1U4dGZ2aTNaQS9YUURBenBrbS9CSHRiRnRydElRWTZrUmVoN0hhOEJBb0dBWDNtWAp1emNMT1EzUzhaSlVmQkZOL090SkljTS9hc29NQVNqMS92bXhFY094WDhRR1UwdDdSSTVxTlRaWk5PTGNFMStrCnprckJrZ0VBTCtIOHd5a0pDdlBvamFtQlZBVWRLTmRvWUx3OG5OZnJlSElQVXRPdXc2NnNiMWlmcFZEa0tTNngKV0JkdE1MR1ZGTGdsYjZpUTZkcjh1TldQRm56SjZWbElpeUVUNEpFQ2dZQlNLb2hlSWJnek9lTjVmSTBqWUZzQwp0ellqN3BxYUZaK2Ywcmp3VFZPQVc3TlFsV25ZU2hBQU9kTExYRC9SUjUrT2dQRjJ4Mlp2c241TWlUTTZESllRCmt2dFZmZms0cDg3YytKQmxJUHlzUlU2M3Zab1VIclMrQ3l6MzJob01DVDFUUVJXMUczUExIRStzanBGMDdqcTIKZ2lJTjZUWWpQYjRIY0w1YlI2NXR2dz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: apache-tls
type: kubernetes.io/tls

---
# Source: apache-webserver/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: apache-ssl-config
data:
    ssl.conf: |
        Listen 443
        LoadModule ssl_module modules/mod_ssl.so
            <VirtualHost *:443>
                ServerName apache.webserver
                DocumentRoot "/usr/local/apache2/htdocs"

                <Directory "/usr/local/apache2/htdocs">
                    Require all granted
                </Directory>
                    SSLEngine on
                    SSLCertificateFile "/usr/local/apache2/conf/tls/tls.crt"
                    SSLCertificateKeyFile "/usr/local/apache2/conf/tls/tls.key"
            </VirtualHost>

---
# Source: apache-webserver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: apache-apache-webserver
  labels:
    helm.sh/chart: apache-webserver-0.1.0
    app.kubernetes.io/name: apache-webserver
    app.kubernetes.io/instance: apache
    app.kubernetes.io/version: "2.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: apache-webserver
    app.kubernetes.io/instance: apache

---
# Source: apache-webserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-apache-webserver
  labels:
    helm.sh/chart: apache-webserver-0.1.0
    app.kubernetes.io/name: apache-webserver
    app.kubernetes.io/instance: apache
    app.kubernetes.io/version: "2.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apache-webserver
      app.kubernetes.io/instance: apache
  template:
    metadata:
      labels:
        helm.sh/chart: apache-webserver-0.1.0
        app.kubernetes.io/name: apache-webserver
        app.kubernetes.io/instance: apache
        app.kubernetes.io/version: "2.4"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      containers:
        - name: apache-webserver
          image: "httpd:2.4"
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/httpd-foreground
          args:
            - "-c"
            - "Include /usr/local/apache2/conf/extra/ssl.conf"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/apache2/conf/tls
              name: tls
              readOnly: true
            - mountPath: /usr/local/apache2/conf/extra/ssl.conf
              name: ssl-config
              readOnly: true
              subPath: ssl.conf
      volumes:
        - name: tls
          secret:
            secretName: apache-tls
        - configMap:
            name: apache-ssl-config
          name: ssl-config

---
# Source: apache-webserver/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-apache-webserver
  labels:
    helm.sh/chart: apache-webserver-0.1.0
    app.kubernetes.io/name: apache-webserver
    app.kubernetes.io/instance: apache
    app.kubernetes.io/version: "2.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "apache.webserver"
      secretName: apache-tls
  rules:
    - host: "apache.webserver"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache-apache-webserver
                port:
                  number: 443
